Models/MyCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HasashinShop.Models
{
    public class MyCart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(Product product, int quantity)
        {
            CartLine line = Lines
            .Where(b => b.Product.ProductID == product.ProductID)
            .FirstOrDefault();
            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        public virtual void RemoveLine(Product Product) =>
        Lines.RemoveAll(l => l.Product.ProductID == Product.ProductID);
        public decimal ComputeTotalValue() =>
        Lines.Sum(e => e.Product.Gia * e.Quantity);
        public virtual void Clear() => Lines.Clear();
    }
    public class CartLine
    {
        public int CartLineID { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using HasashinShop.Models;
using System.Linq;

namespace HasashinShop.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private MyCart cart;
        public OrderController(IOrderRepository repoService, MyCart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Trong giỏ hàng rỗng");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }   
}
   

Pages/MyCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HasashinShop.MyTagHelper;
using HasashinShop.Models;
using System.Linq;
namespace HasashinShop.Pages
{
    public class MyCartModel : PageModel
    {
        private IHasashinShopRepository repository;
        public MyCartModel(IHasashinShopRepository repo, MyCart myCartService)
        {
            repository = repo;
            myCart = myCartService;
        }
        public MyCart myCart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(long productID, string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(b => b.ProductID == productID);
            myCart.AddItem(product, 1);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long productID, string returnUrl)
        {
            myCart.RemoveLine(myCart.Lines.First(cl =>
            cl.Product.ProductID == productID).Product);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Completed.cshtml
@page
<div class="text-center">
    <h3>Cảm ơn bạn đã đặt hàng #@OrderId</h3>
    <p>Chúng tôi sẽ vận chuyển nhanh và an toàn cho bạn.</p>
    <a class="btn btn-success" asp-controller="Home">Về trang chủ</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string OrderId { get; set; }
}

Pages/MyCart.cshtml
@page
@model MyCartModel
@{ var format = System.Globalization.CultureInfo.GetCultureInfo("vi-VN"); }

<h2>Giỏ hàng</h2>
<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>Hình ảnh</th>
            <th>Số lượng</th>
            <th>Sản phẩm</th>
            <th class="text-right">Giá</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.myCart.Lines)
         {
            <tr>
                <td class="text-center"><img src="@line.Product.ImageProduct" asp-append-version="true" width="150" height="100" /></td>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.TenSP</td>
                <td class="text-right">@String.Format(format, "{0:c0}", line.Product.Gia)</td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="ProductID"
                               value="@line.Product.ProductID" />
                        <input type="hidden" name="returnUrl"
                               value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
         }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Tổng cộng: </td>
            <td class="text-right">
                @String.Format(format, "{0:c0}", Model.myCart.ComputeTotalValue())
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-right">
    <a class="btn btn-success" href="@Model.ReturnUrl"><i class='fas fa-arrow-left mr-2'></i>Quay lại</a>
    <a class="btn btn-danger" asp-action="Checkout" asp-controller="Order">
        Thanh toán<i class="fa fa-check ml-2"></i>
    </a>
</div>